# Generated by Django 4.1.4 on 2023-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0002_remove_client_acheter_client_adressec_client_nomc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='AdresseF',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='NomF',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='PrenomF',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='TelephoneF',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
