# Generated by Django 4.1.4 on 2023-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0003_fournisseur_adressef_fournisseur_nomf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='CodeP',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
