# Generated by Django 4.1.4 on 2023-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0005_alter_produit_codep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='CodeP',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
