# Generated by Django 4.1.4 on 2023-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0006_alter_produit_codep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='CodeF',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeproduit',
            name='CodeT',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
