# Generated by Django 4.1.4 on 2023-01-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0011_facture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
