# Generated by Django 4.1.4 on 2023-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0012_delete_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='AdresseC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='NomC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='PrenomC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='TelephoneC',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='AdresseF',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='NomF',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='PrenomF',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='TelephoneF',
            field=models.CharField(default='', max_length=100),
        ),
    ]
