# Generated by Django 4.1.4 on 2023-01-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0013_alter_client_adressec_alter_client_nomc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('CodeS', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField(default=0)),
                ('PrixHT', models.IntegerField(default=0)),
                ('PrixVente', models.IntegerField(default=0)),
                ('date', models.DateField(default=0)),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.produit')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.typeproduit')),
            ],
        ),
    ]
