# Generated by Django 4.1.4 on 2023-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0014_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unecommande',
            name='product',
        ),
        migrations.AddField(
            model_name='stock',
            name='TotalAchat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='TotalVente',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='BonDeCommande',
        ),
        migrations.DeleteModel(
            name='UneCommande',
        ),
    ]
