# Generated by Django 4.1.4 on 2023-01-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0015_remove_unecommande_product_stock_totalachat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
