# Generated by Django 4.1.4 on 2023-01-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0017_remove_stock_totalachat_remove_stock_totalvente'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteComptoir',
            fields=[
                ('CodeVente', models.CharField(default=' ', max_length=20, primary_key=True, serialize=False)),
                ('Qte', models.IntegerField(default=0)),
                ('MontantPaye', models.FloatField(default=0)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.client')),
                ('PrixVente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.stock')),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.produit')),
            ],
        ),
    ]
