# Generated by Django 4.1.4 on 2023-01-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0023_alter_ventecomptoir_codevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Fournisseur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.fournisseur'),
        ),
    ]
