# Generated by Django 4.1.4 on 2023-01-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0024_produit_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestStockMagasin.fournisseur'),
        ),
    ]
