# Generated by Django 4.1.4 on 2023-01-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0025_alter_produit_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventecomptoir',
            name='CodeVente',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
