# Generated by Django 4.1.3 on 2023-01-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestStockMagasin', '0027_alter_ventecomptoir_codevente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Produit',
            new_name='produit',
        ),
    ]
